### ISSUE TITLE
导出为图片功能失效，无法在浏览器弹出图片。其他主题或者默认主题可以

### ISSUE THREAD

**Issue by pakeh2866** [mustakshif/Asri#106]
![image](https://github.com/user-attachments/assets/68cfa918-2b8f-423e-8080-9bc49d2d8296)

**Comment by mustakshif** [comment]
收到，感谢反馈

**Comment by mustakshif** [comment]
已修复，请下载最新 [theme.css](https://github.com/mustakshif/Asri/blob/main/theme.css) 替换本地文件，以及更新思源版本到最新版
