### ISSUE TITLE
loss todo ico

### ISSUE THREAD

**Issue by cly2625** [mustakshif/Asri#113]
![image](https://github.com/user-attachments/assets/7c09571f-402f-4a07-8671-cdebf5f2f79e)

**Comment by mustakshif** [comment]
I'm unable to reproduce this issue. Could you please review your CSS snippets for any potential style conflicts or cascading interferences?

**Comment by cly2625** [comment]
It conflicts with [headingIndex](https://github.com/leolee9086/headingIndex) ![image](https://github.com/user-attachments/assets/c06bfbeb-6e50-4f97-ba7c-530e80f11929)

**Comment by mustakshif** [comment]
Thank you for your feedback. Already solved. You can download the latest [theme.css](https://github.com/mustakshif/Asri/blob/main/theme.css) file and replace your local version for immediate resolution.
