### ISSUE TITLE
slash command menu doesn't support the use of left and right direction keys

### ISSUE THREAD

**Issue by noisnemid** [mustakshif/Asri#114]
Asri is so great a theme, and the big expanded and self-adapting slash command menu is wonderful!
But I found the slash command menu could not use the left and right direction keys to select items.
I wonder if there might be a possibility to enable this function? It would be really nice if it could. ;-)

**Comment by mustakshif** [comment]
Thank you for your appreciation of Asri! The slash menu in SiYuan was originally designed as a single-column list, so horizontal navigation wasn't considered in its initial design. All I did was use CSS to make it expandable. You make a good point that supporting horizontal navigation in the expanded view would enhance the user experience. However, I believe the most efficient navigation method is to use <kbd>/</kbd> + <kbd>item initials</kbd> (for example, <kbd>/ d a t</kbd> to add a database block) or to use keyboard shortcuts instead.
