### ISSUE TITLE
If possible, it is hoped that a hollowing function is built in, like the Savor theme in the image and video below.

### ISSUE THREAD

**Issue by Tisamn** [mustakshif/Asri#116]
https://github.com/user-attachments/assets/d147d0e6-282d-405e-abd8-11d69e7417bd

![image](https://github.com/user-attachments/assets/89bcbcf3-f6d1-42c0-b357-268532744181)

**Comment by mustakshif** [comment]
Thank you for your feedback. Will consider implementing this feature in future dev process

**Comment by mustakshif** [comment]
Hey, looks like there's already a plugin that does exactly what you asked for, and it's pretty good! I'll go ahead and close this issue.

<img width="418" alt="image" src="https://github.com/user-attachments/assets/62a374df-0193-460d-9066-f59f71552a5b">
