### ISSUE TITLE
文档树展开动画卡顿

### ISSUE THREAD

**Issue by itWhale233** [mustakshif/Asri#118]
> SiYuan 版本： v3.1.14
> Arsi 主题版本：v3.1.19

默认主题展开动画：
![github-normal](https://github.com/user-attachments/assets/f42a8d7e-1a6f-407b-86ad-55757579b938)

Asri 主题展开动画：
![github-issues](https://github.com/user-attachments/assets/8a882537-98ee-4e93-83e4-6376ce7ec86c)

有比较明显的顿挫感看看能不能优化一下

**Comment by mustakshif** [comment]
感谢反馈，已修复。可下载最新 [theme.css](https://github.com/mustakshif/Asri/blob/main/theme.css) 替换本地文件即可
