### ISSUE TITLE
右边侧边栏的布局问题

### ISSUE THREAD

**Issue by dsu-k** [mustakshif/Asri#119]
程序和主题版本都是保持最新
## 服务器docker端
由于没有右上角三个按钮，右侧栏会被拉高，但展开界面会向下错位，但最上方的图标位置没有变
![image](https://github.com/user-attachments/assets/7d7031b8-d61c-468b-a0f3-4bfe2bac7633)
![image](https://github.com/user-attachments/assets/cc70db4e-4b2b-4501-a205-81f70cc3c896)
## 桌面端
右侧栏高度没有问题，但展开时最上方图标会被向左推
![image](https://github.com/user-attachments/assets/324bda0b-a8ac-4a01-b5d3-64c5bf8b381d)
![image](https://github.com/user-attachments/assets/dda7aefb-1fb7-47a7-9c08-dfd689734a47)

**Comment by mustakshif** [comment]
感谢反馈。以上都是正常的，设计如此。

> ![image](https://private-user-images.githubusercontent.com/81206855/393487475-dda7aefb-1fb7-47a7-9c08-dfd689734a47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NTkzMjcsIm5iZiI6MTczMzU1OTAyNywicGF0aCI6Ii84MTIwNjg1NS8zOTM0ODc0NzUtZGRhN2FlZmItMWZiNy00N2E3LTljMDgtZGZkNjg5NzM0YTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA4MTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YWE1OWQ1ZmRlNTI2ODAxOThmODNjNDRkYTY0ZGM0MmEzMzFhOTJiY2MxNzMwMTMxNThjMWFlZGIyOTQ1YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.51Z9xWuvpYPBYoLnzFzQ3ZqlFKslYhY3So6StpJbXC4)

顶栏图标是动态布局的，当右侧面板宽度足够容纳所有插件图标时，这些图标就不会被挤出；你可以尝试拉宽右侧面板或者可以适当取消钉住部分图标
