### ISSUE TITLE
Ideas for Bringing Cupertino Theme Elements into Asri

### ISSUE THREAD

**Issue by UsmanTechJive** [mustakshif/Asri#120]
Hello! First, I want to express my gratitude for all the hard work you've put into the Asri theme. It's the only long term theme I've consistently used, and I truly appreciate it.

I recently discovered a theme called [Cupertino for Obsidian](https://www.reddit.com/rObsidianMD/comments1hogoxe/cupertino_is_now_available_incommunity_theme/), which I find to be one of the best-designed themes in Obsidian. I believe some of its design elements could further enhance Asri if you take some inspiration from it.

Here are specific features from Cupertino that I'd love to see in Asri:

- Document Area: Shadows, rounded corners and borders around the document area.
- Pop-up Shadows: Shadows behind pop-ups add depth. SiYuan already has shadows, but I think they could be improved.
- Line Highlighting: An indicator showing the current line.
- Sidebar Animation: The opening and closing animation of the sidebar panel is amazing and creates such an immersive experience that you have to experience it firsthand.
- Tab Switching Animation: There's an animation when users switch tabs.
- Attention to Detail: Other minor tweaks such as switches, buttons etc.

Thank you for considering these suggestions. I really think that bringing in these elements could make Asri an even more amazing theme for Siyuan.

![image](https://github.com/user-attachments/assets/408cdb47-cdd6-46e8-a551-2079f1bf0852)

Settings:

![image](https://github.com/user-attachments/assets/adbadf7d-80a8-45c3-9f3c-ea944e96595b)

Sidebar Panel Animation:

![image](https://github.com/user-attachments/assets/b621b3a7-8c0c-4a86-9a21-a7041149e646)

Tabs Switching Animation:

https://github.com/user-attachments/assets/c3b661bf-c4f0-4833-b26d-17796d490b0d

Panel Actions Auto-Hiding Animation:

https://github.com/user-attachments/assets/8e469699-7ce8-4bb4-a7b8-cdc1a3374304

You can create a similar auto-hiding animation for panel actions here as well.

![image](https://github.com/user-attachments/assets/5916286e-ad9d-4eea-ba08-e52c79e8bc52)

Notifications:

![image](https://github.com/user-attachments/assets/fb43012f-8e8c-44aa-a4cc-9a8cdf6b62b5)

Blur effect behind the doc breadcrumb area. It's hard to see on Windows but may be more visible on Mac.

![image](https://github.com/user-attachments/assets/80fac66e-a708-428b-af37-c0ab78ee1e6e)

Assets Pop Up Window:
I think this UI is better. We can see all of the assets clearly. At the top, we have a full-width search bar, making it easier to type and search.

![image](https://github.com/user-attachments/assets/99f729e0-7c08-4e5d-8266-ee1e310bcc59)

**Note: I'd highly recommend experiencing all of these firsthand to really get a sense of what I'm describing.**

**Comment by mustakshif** [comment]
Thank you so much for your suggestion! It looks absolutely wonderful. I've installed Obsidian on my system. I'll proceed to download the theme and give it a personal try to see what creative ideas I can gather from it 😉

**Comment by UsmanTechJive** [comment]
> Thank you so much for your suggestion! It looks absolutely wonderful. I've installed Obsidian on my system. I'll proceed to download the theme and give it a personal try to see what creative ideas I can gather from it 😉

Glad to hear that, Let's Make ASRI Great Again! 😁

**Comment by mustakshif** [comment]
Here's the improved version while maintaining your style:

> * Document Area: Shadows, rounded corners and borders around the document area.
> * Pop-up Shadows: Shadows behind pop-ups add depth. SiYuan already has shadows, but I think they could be improved.
> * Line Highlighting: An indicator showing the current line.
> * Sidebar Animation: The opening and closing animation of the sidebar panel is amazing and creates such an immersive experience that you have to experience it firsthand.
> * Tab Switching Animation: There's an animation when users switch tabs.
> * Attention to Detail: Other minor tweaks such as switches, buttons etc.

- Document Area: Won't change, as it's a completely different style than Asri
- Shadows: Will remain as is, since I prefer light shadows for a cleaner visual look
- Line Highlighting: Implemented ✅
- Sidebar Animation: not possible, limited to improving the animation curve
- Tab Switching Animation: Implemented ✅ with a simpler, slightly different version
- Details: Looking good as they are 😎, but I'm open to suggestions

> Panel Actions Auto-Hiding Animation:

Done ✅

> Notifications:

Done ✅

> Blur effect behind the doc breadcrumb area. It's hard to see on Windows but may be more visible on Mac.

This feature is currently in testing and will be implemented in future releases

> Assets Pop Up Window:

Doesn't appear to be possible.

Thank you for your appreciation and focus on making Asri better and "GREAT again" as you mentioned. I'm currently working on the v3.2.0 release, and your suggestions have significantly enriched this update. Thank you again 🙏.

**Comment by UsmanTechJive** [comment]
Awesome work overall, thanks for listening. I appreciate it.

Ah, I really wish that sidebar immersive animation was possible, but it's okay.

- Document Area: Won't change, as it's a completely different style than Asri

I think this is possible because I'm using your theme + my own custom css & js. So I guess you can achieve this.

![image](https://github.com/user-attachments/assets/8545bbed-4f83-492c-8998-04f4d70193d5)

You could improve the dark mode colors a bit to mimic the look.

![image](https://github.com/user-attachments/assets/2dff526a-db2e-4c39-b12b-eeab79268108)

Looking forward to the 'blur effect behind the doc breadcrumb area.' I've always wanted this.

Hmm... regarding the Assets UI redesign, I guess I have to create a separate request in the SiYuan repo.

For details: I think it would be better if you could work on making the buttons (settings, etc.) and switches more like iOS, similar to the Cupertino Obsidian theme style.

**Comment by UsmanTechJive** [comment]
The animation looks dope, but I think it needs a little optimization.

ASRI:

https://github.com/user-attachments/assets/419f270f-110a-47be-a38a-17df8c859059

Cupertino:

https://github.com/user-attachments/assets/938850e3-b2ca-400a-83c0-b676612afca0

**Comment by mustakshif** [comment]
> Ah, I really wish that sidebar immersive animation was possible, but it's okay.

Yes. This won't be possible until SiYuan's developers implement it.

> * Document Area: Won't change, as it's a completely different style than Asri
> 
> I think this is possible because I'm using your theme + my own custom css & js. So I guess you can achieve this.

I know it's technically possible. What I mean is that the vertical column layout is what defines Asri's identity. While wrapping document content in a rectangle looks clean and familiar to most users, it follows a different design approach. But hey, you can always customize the editor UI however you want using code snippets, and you've done an excellent job with it!

> You could improve the dark mode colors a bit to mimic the look when chroma sets to 0 and scrollbars color as well.

> Edit: Also, you could add an option here similar to Obsidian, where the document background remains dark without added colors. This way, users could choose between the current chroma style we have in ASRI or keep the background without colors, rest applies.

This is also achievable through code snippets. By overriding color variables for the .protyle element, you can keep the editor background color unchanged while customizing colors for other interface elements.

> For details: I think it would be better if you could work on making the buttons (settings, etc.) and switches more like iOS, similar to the Cupertino Obsidian theme style.

Currently, Asri buttons and components use a flat visual style. The Cupertino theme actually follows macOS design principles rather than iOS, creating a more "realistic" look through subtle shadows and gradient colors. I'm hesitant to add these effects in SiYuan because its interface sometimes can contain *MANY* of these components - too many shadows and gradients could create visual noise. While the current Asri components might look plain, **I'll continue exploring new style options.**

If you mean grouping the settings interface like iOS or Cupertino - that's tricky due to SiYuan's flat DOM structure for setting items. While I could count and visually group setting items, it would add unnecessary complexity and make future maintenance harder.

**Comment by UsmanTechJive** [comment]
> 
> > You could improve the dark mode colors a bit to mimic the look when chroma sets to 0 and scrollbars color as well.
> 
> > Edit: Also, you could add an option here similar to Obsidian, where the document background remains dark without added colors. This way, users could choose between the current chroma style we have in ASRI or keep the background without colors, rest applies.
> 
> This is also achievable through code snippets. By overriding color variables for the .protyle element, you can keep the editor background color unchanged while customizing colors for other interface elements.
> 

I think it would be great if you could add this option yourself, perhaps as a switch, so users who don't want to apply chroma colors to the document background can disable it easily. Sometimes I like to have it enabled, and sometimes I don't - it depends on the color I've applied. I hope you understand my point, this feature would make life easier.

Also, if I want to modify the background color when the chroma is set to 0 in dark mode, how can I do this with a CSS snippet? I mean how can I check this condition?

**Comment by mustakshif** [comment]
> I think it would be great if you could add this option yourself, perhaps as a switch, so users who don't want to apply chroma colors to the document background can disable it easily. Sometimes I like to have it enabled, and sometimes I don't - it depends on the color I've applied. I hope you understand my point, this feature would make life easier.

You made a good point. I'll consider this.



> Also, if I want to modify the background color when the chroma is set to 0 in dark mode, how can I do this with a CSS snippet? I mean how can I check this condition?

```css
:root[style*="--asri-c-factor: 0"] {

}
```

**Comment by UsmanTechJive** [comment]
> > I think it would be great if you could add this option yourself, perhaps as a switch, so users who don't want to apply chroma colors to the document background can disable it easily. Sometimes I like to have it enabled, and sometimes I don't - it depends on the color I've applied. I hope you understand my point, this feature would make life easier.
> 
> You made a good point. I'll consider this.
> 
> > Also, if I want to modify the background color when the chroma is set to 0 in dark mode, how can I do this with a CSS snippet? I mean how can I check this condition?
> 
> ```css
> :root[style*="--asri-c-factor: 0"] {
> 
> }
> ```

I've tried this, but as you can see, the borders in the Obsidian Cupertino theme are sharp while my borders are not. If I use 1px, then it's too light and thin, barely visible compared to the Cupertino theme, and behind the doc, there is a shadow. How can I achieve similar shadows? The problem is that sometimes it's cutting off.

![image](https://github.com/user-attachments/assets/81286328-a600-473d-8870-ea4df2265ec5)

Here is my CSS:

```
:root[style*="--asri-c-factor: 0"]:where(html[data-theme-mode="dark"][data-dark-theme="Asri"]) {
    /* Defines the color scheme and custom properties for dark themes */
    color-scheme: dark !important;
    /* --b3-theme-primary: rgb(254, 231, 0) !important; */ /* rgb(254, 231, 0) */
       --b3-theme-background: rgba(30, 30, 30, 1) !important; /* rgba(18, 20, 22, 1) */
    /* --b3-border-color: hsl(0, 0%, 16%) !important; */
       --b3-theme-surface: rgba(38, 38, 38, 1) !important; /* rgba(12, 14, 16, 1) */
    /* --b3-menu-background: rgba(11, 11, 11, 1) !important; */
    /* --b3-menu-item-background-hover: rgb(123, 97, 179) !important; */
    /* --b3-border-color: hsl(0, 0%, 0%) !important; */
}

:root[style*="--asri-c-factor: 0"]:where(html[data-theme-mode="light"][data-dark-theme="Asri"]) {
    /* Defines the color scheme and custom properties for dark themes */
    color-scheme: dark !important;
    /* --b3-theme-primary: rgb(254, 231, 0) !important; */ /* rgb(254, 231, 0) */
       --b3-theme-background: rgba(255,255,255, 1) !important; /* rgba(18, 20, 22, 1) */
    /* --b3-border-color: hsl(0, 0%, 16%) !important; */
       --b3-theme-surface: rgba(246, 246, 246, 1) !important; /* rgba(12, 14, 16, 1) */
    /* --b3-menu-background: rgba(11, 11, 11, 1) !important; */
    /* --b3-menu-item-background-hover: rgb(123, 97, 179) !important; */
    /* --b3-border-color: hsl(0, 0%, 0%) !important; */
}
```

Another CSS for borders:

```
html[data-theme-mode="dark"][data-dark-theme="Asri"] {
    /* Border */
    .protyle-preview {
      border: 2px solid var(--b3-border-color-trans) !important;  /* var(--b3-border-color-trans) */
    }

    /* Document - Border */
    .protyle {
      border: 2px solid var(--b3-border-color-trans) !important;
    }

    /* Webview - Border */
    webview {
      border: 2px solid var(--b3-border-color-trans) !important;
    }

    /* Excelidraw Window Content - Border */
    .excalidraw-wrapper{
    }
}

:root[style*="--asri-c-factor: 0"]:where(html[data-theme-mode="dark"][data-dark-theme="Asri"]) {
    /* Border */
    .protyle-preview {
      border: 1.5px solid rgba(244,244,244,.12) !important;  /* var(--b3-border-color-trans) */
    }

    /* Document - Border */
    .protyle {
      border: 1.5px solid rgba(244,244,244,.12) !important;
    }

    /* Webview - Border */
    webview {
      border: 1.5px solid rgba(244,244,244,.12) !important;
    }

    /* Excelidraw Window Content - Border */
    .excalidraw-wrapper{
    }
}


:root[style*="--asri-c-factor: 0"]:where(html[data-theme-mode="light"][data-dark-theme="Asri"]) {
    /* Border */
    .protyle-preview {
      border: 1.5px solid rgba(31,34,37,.09) !important;  /* var(--b3-border-color-trans) */
    }

    /* Document - Border */
    .protyle {
      border: 1.5px solid rgba(31,34,37,.09) !important;
    }

    /* Webview - Border */
    webview {
      border: 1.5px solid rgba(31,34,37,.09) !important;
    }

    /* Excelidraw Window Content - Border */
    .excalidraw-wrapper{
    }
}



```

**Comment by mustakshif** [comment]
I found a solution:

```css
.layout__center {
    overflow: visible;
    z-index: 1;

    >.fn__flex-1 {
        overflow: visible;

        >[data-type="wnd"] {
            overflow: visible;

            >.layout-tab-container {
                box-shadow: rgba(244,244,244,.12) 0px 0px 0px 1px, rgba(0,0,0,.16) 0px 24px 48px, rgba(0,0,0,.12) 0px 4px 16px, 0 0 40px red;
            }
        }
    }
}

```

To test this, first remove the existing code snippets. The Cupertino-style border and shadow effect is achieved purely through the box-shadow property - I've copied it directly from Obsidian and added a red shadow for visualization purposes, which you can remove later. Quick note: modifying overflow and z-index properties requires caution, but I haven't run into any problems during my brief testing.

**Comment by UsmanTechJive** [comment]
> I found a solution:
> 
> ```css
> .layout__center {
>     overflow: visible;
>     z-index: 1;
> 
>     >.fn__flex-1 {
>         overflow: visible;
> 
>         >[data-type="wnd"] {
>             overflow: visible;
> 
>             >.layout-tab-container {
>                 box-shadow: rgba(244,244,244,.12) 0px 0px 0px 1px, rgba(0,0,0,.16) 0px 24px 48px, rgba(0,0,0,.12) 0px 4px 16px, 0 0 40px red;
>             }
>         }
>     }
> }
> ```
> 
> To test this, first remove the existing code snippets. The Cupertino-style border and shadow effect is achieved purely through the box-shadow property - I've copied it directly from Obsidian and added a red shadow for visualization purposes, which you can remove later. Quick note: modifying overflow and z-index properties requires caution, but I haven't run into any problems during my brief testing.

Gonna try this now, thanks.



I just have one thing in mind. What if you add some nice animation when the user clicks this, and when hiding/showing it, it shows a smooth transition animation? Is that possible?

![image](https://github.com/user-attachments/assets/df9be512-a5c0-432b-8604-b4be875a4ae6)

**Comment by UsmanTechJive** [comment]
> I found a solution:
> 
> ```css
> .layout__center {
>     overflow: visible;
>     z-index: 1;
> 
>     >.fn__flex-1 {
>         overflow: visible;
> 
>         >[data-type="wnd"] {
>             overflow: visible;
> 
>             >.layout-tab-container {
>                 box-shadow: rgba(244,244,244,.12) 0px 0px 0px 1px, rgba(0,0,0,.16) 0px 24px 48px, rgba(0,0,0,.12) 0px 4px 16px, 0 0 40px red;
>             }
>         }
>     }
> }
> ```
> 
> To test this, first remove the existing code snippets. The Cupertino-style border and shadow effect is achieved purely through the box-shadow property - I've copied it directly from Obsidian and added a red shadow for visualization purposes, which you can remove later. Quick note: modifying overflow and z-index properties requires caution, but I haven't run into any problems during my brief testing.

Okay, so I've tested it and the red glow/shadow looks cool lol, but there are some issues. In certain views it works fine, but in some views the shadow is getting cut off, as you can see in the video.

With all of my CSS and JS snippets enabled:

https://github.com/user-attachments/assets/d5bf23d7-65f1-4bca-9b0b-3ad0ecefdf28

Without any custom CSS and JS:

https://github.com/user-attachments/assets/7217ed36-578e-4184-a742-4d55e3dc1ff1

**Comment by mustakshif** [comment]
> I just have one thing in mind. What if you add some nice animation when the user clicks this, and when hiding/showing it, it shows a smooth transition animation? Is that possible?
> 
> ![image](https://private-user-images.githubusercontent.com/36538038/399390349-df9be512-a5c0-432b-8604-b4be875a4ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MjIwNzAsIm5iZiI6MTczNTYyMTc3MCwicGF0aCI6Ii8zNjUzODAzOC8zOTkzOTAzNDktZGY5YmU1MTItYTVjMC00MzJiLTg2MDQtYjRiZTg3NWE0YWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA1MDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NWQ1OGNmMzRiOTMyNjlmYmJlZjQ0ZTNjMjc0YmIxMDMyNTQ2MWViMmFlNmRmY2Y2Zjc3YzFhZGQzYzJkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mCgXrKiVaVAH50yrYDMn5PtfmexnpzwbMgZbFfWAoFs)

Same as the side panel animation, not possible.



> but in some views the shadow is getting cut off, as you can see in the video.

In Cupertino shadow of doc area is disabled when expanded. You can achieve that by adding a selector:

```css
.dock-layout-expanded+#layouts {
    .layout__center {
        overflow: visible;
        z-index: 1;

        >.fn__flex-1 {
            overflow: visible;

            >[data-type="wnd"] {
                overflow: visible;

                >.layout-tab-container {
                    box-shadow: rgba(244, 244, 244, .12) 0px 0px 0px 1px, rgba(0, 0, 0, .16) 0px 24px 48px, rgba(0, 0, 0, .12) 0px 4px 16px, 0 0 40px red;
                }
            }
        }
    }
}

.layout-tab-container {
    transition: box-shadow .2s;
}

```

**Comment by UsmanTechJive** [comment]
> > I just have one thing in mind. What if you add some nice animation when the user clicks this, and when hiding/showing it, it shows a smooth transition animation? Is that possible?
> > ![image](https://private-user-images.githubusercontent.com/36538038/399390349-df9be512-a5c0-432b-8604-b4be875a4ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MjIwNzAsIm5iZiI6MTczNTYyMTc3MCwicGF0aCI6Ii8zNjUzODAzOC8zOTkzOTAzNDktZGY5YmU1MTItYTVjMC00MzJiLTg2MDQtYjRiZTg3NWE0YWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA1MDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NWQ1OGNmMzRiOTMyNjlmYmJlZjQ0ZTNjMjc0YmIxMDMyNTQ2MWViMmFlNmRmY2Y2Zjc3YzFhZGQzYzJkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mCgXrKiVaVAH50yrYDMn5PtfmexnpzwbMgZbFfWAoFs)
> 
> Same as the side panel animation, not possible.
> 
> > but in some views the shadow is getting cut off, as you can see in the video.
> 
> In that case, you'll need to set the overflow property to visible for all parent elements to make it work. Also, note that in Cupertino, the document area's shadow disappears when expanded.
> 
> I've implemented all these changes in the snippet below:
> 
> ```css
> .dock-layout-expanded+#layouts {
>     overflow: visible;
> 
>     >.fn__flex-1:first-child {
>         overflow: visible;
>     }
> 
>     .layout__center {
>         overflow: visible;
>         z-index: 1;
> 
>         >.fn__flex-1 {
>             overflow: visible;
> 
>             >[data-type="wnd"] {
>                 overflow: visible;
> 
>                 >.layout-tab-container {
>                     box-shadow: rgba(244, 244, 244, .12) 0px 0px 0px 1px, rgba(0, 0, 0, .16) 0px 24px 48px, rgba(0, 0, 0, .12) 0px 4px 16px, 0 0 40px red;
>                 }
>             }
>         }
>     }
> }
> 
> .layout-tab-container {
>     transition: box-shadow .2s;
> }
> ```

Awesome, this is working great.

Now, all I want is to apply a box-shadow when only the right panel is expanded and the left panel is not expanded.

![image](https://github.com/user-attachments/assets/a831852a-8cae-452b-8690-cf3cad89987f)

**Comment by mustakshif** [comment]
> Now, all I want is to apply a box-shadow when only the right panel is expanded and the left panel is not expanded.


Similar problem as in #108. Please refer to https://github.com/mustakshif/Asri/issues/108#issuecomment-2452811546 to see if it helps

**Comment by UsmanTechJive** [comment]
> > Now, all I want is to apply a box-shadow when only the right panel is expanded and the left panel is not expanded.
> 
> Similar problem as in #108. Please refer to selectors mentioned in [#108 (comment)](https://github.com/mustakshif/Asri/issues/108#issuecomment-2452811546) to see if that helps

I tried those selectors, but in the end this one worked nicely.

Fix:
```
/* When Left Not Expanded && Right Expanded */
#dockLeft:not(.dock-layout-expanded)+#layouts:has(.layout__dockr:not(.layout--float))
```

CSS:
```
html[data-theme-mode="dark"][data-dark-theme="Asri"] {
.dock-layout-expanded+#layouts,
#dockLeft:not(.dock-layout-expanded)+#layouts:has(.layout__dockr:not(.layout--float))
 {
    overflow: visible;

    >.fn__flex-1:first-child {
        overflow: visible;
    }

    .layout__center {
        overflow: visible;
        z-index: 1;

        >.fn__flex-1 {
            overflow: visible;

            >[data-type="wnd"] {
                overflow: visible;

                >.layout-tab-container {
                    box-shadow: rgba(244, 244, 244, .12) 0px 0px 0px 1px, rgba(0, 0, 0, .16) 0px 24px 48px, rgba(0, 0, 0, .12) 0px 4px 16px;
                    border-radius: 13px !important;
                }
            }
        }
    }
  }
}
```

**Comment by UsmanTechJive** [comment]
> 
> Assets Pop Up Window: I think this UI is better. We can see all of the assets clearly. At the top, we have a full-width search bar, making it easier to type and search.
> 
> ![image](https://private-user-images.githubusercontent.com/36538038/399133655-99f729e0-7c08-4e5d-8266-ee1e310bcc59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwODgzODQsIm5iZiI6MTczNjA4ODA4NCwicGF0aCI6Ii8zNjUzODAzOC8zOTkxMzM2NTUtOTlmNzI5ZTAtN2MwOC00ZTVkLTgyNjYtZWUxZTMxMGJjYzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDE0NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNTFlMDA5NTdlMjA0M2Q3ZTY4NDc4ZTYzNDc5NzNhOTMyZjE0OTI1MGVhMWI3OTk2YjNkMGE0YWE0NzRlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nn2d9IKKj8P1W77OraOyhVzLyOw9SrEjsIN5cXMZ0x8)
> 
> **Note: I'd highly recommend experiencing all of these firsthand to really get a sense of what I'm describing.**


I created these concept designs in Figma to illustrate my suggestions. I'll create a request in the SiYuan GitHub repo. Even if they add support for waterfall or grid layouts with search bar functionality, I think you could turn these concepts into reality with your theme, as I know they won't implement these modern styles but functionality.

Settings - Assets:
<img width="1216" alt="Settings - Assets" src="https://github.com/user-attachments/assets/6b588818-b1b8-4477-8900-d48ac4c1f8ce" />

Assets Dialog:

<img width="1216" alt="Assets Dialog" src="https://github.com/user-attachments/assets/cc1eb4d7-0b44-47a7-b177-3286bd27d7d3" />

**Comment by mustakshif** [comment]
These concept designs look awesome! Your request is truly valuable. If they implement this functionality, it will definitely make searching assets much easier, and I'll certainly do my best to make the interface look nice. I'm really looking forward to it!

**Comment by UsmanTechJive** [comment]
> These concept designs look awesome! Your request is truly valuable. If they implement this functionality, it will definitely make searching assets much easier, and I'll certainly do my best to make the interface look nice. I'm really looking forward to it!

I have submitted my feature request [here](https://github.com/siyuan-note/siyuan/issues/13731):
