### ISSUE TITLE
最新版本更新后“打字机插件”无法使用

### ISSUE THREAD

**Issue by Tim-Devil** [mustakshif/Asri#121]
目前只有（应该是主题自带的）左边一根蓝条指示位置，但是本来按理说打字机插件应该是可以显示一个蓝框的。
私以为蓝框更直观。不知道是不是这个主题的问题。

**Comment by mustakshif** [comment]
感谢反馈。是主题原因，现已修复。下载最新的 [theme.css](https://github.com/mustakshif/Asri/blob/main/theme.css) 替换本地版本即可
