### ISSUE TITLE
Elements of topbar and doc cover img area would overlap in certain circumstances

### ISSUE THREAD

**Issue by mustakshif** [mustakshif/Asri#25]
部分情况下顶栏布局重叠且不自动刷新，在新小窗页签以分屏形式拖回主窗口、清空页签后打开新页签、添加文档标签等场景复现。

**在主界面单击任意位置可解决。**
**Click anywhere in the main window to fix this.**

**Comment by 5kyfkr** [comment]
这个我还发现一个稳定复现的方法，就是把所有页签关了后，然后再打开一个页签，就会触发

**Comment by mustakshif** [comment]
> 这个我还发现一个稳定复现的方法，就是把所有页签关了后，然后再打开一个页签，就会触发

好哦。目前没有发现很好的解决方法，只能手动点击一下了

**Comment by 5kyfkr** [comment]
> > 这个我还发现一个稳定复现的方法，就是把所有页签关了后，然后再打开一个页签，就会触发
> 
> 好哦。目前没有发现很好的解决方法，只能手动点击一下了

问题不大，一般都会固定一个标签页，就是第一次启动的时候要点一下
