### ISSUE TITLE
数据库属性按钮被遮挡

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#26]
如下图，当仅有题头图片的时候悬浮按钮会遮挡数据库按钮，无题图和有文档表情符号下无问题
![image](https://github.com/mustakshif/Asri/assets/63196026/3f7629fc-68bd-4c51-b29d-90b69edebb55)
![image](https://github.com/mustakshif/Asri/assets/63196026/0a774c4f-9341-48c1-9ac4-6145c4819d18)

**Comment by mustakshif** [comment]
感谢反馈，下个版本修复
