### ISSUE TITLE
Animation lag and stability issues occur when opening right-side doc apps or graphs.

### ISSUE THREAD

**Issue by MrIntellectX** [mustakshif/Asri#28]
When I click on the right doc icon, for example, the Web App, it opens with a stable animation on SiYuan's default dark theme, as you can see here:

Video: Without Custom Snippets + Default Dark Theme

https://github.com/mustakshif/Asri/assets/36538038/0fb26ef7-1052-49fd-83e5-1ca24d481dc4

However, when I open it in the Asri Dark Theme, the animation is not as smooth and stable. There is also a kind of lag when opening the web app, and this issue occurs with others like the graph, etc.

Video: Without Custom Snippets + Asri Dark Theme

https://github.com/mustakshif/Asri/assets/36538038/b96211c4-34f2-489b-acc8-038d2ff16f59

And it is more visible when using my own custom CSS snippets.

Video: With Custom CSS Snippets + Asri Dark Theme

https://github.com/mustakshif/Asri/assets/36538038/c3f4990a-6064-48b3-9f03-cdf347888646

It would be great if you could achieve smooth animation like Obsidian.

Video: Obsidian right panel animation

https://github.com/mustakshif/Asri/assets/36538038/5cb3fdcb-bd1c-4310-874d-c62da22e69a7

**Comment by mustakshif** [comment]
Thank you for reporting this issue.

I tested on my device, and it looked fine:

https://github.com/mustakshif/Asri/assets/100056458/b3290d18-cc6f-410e-9b03-0aee711f3283

If you're running SiYuan in a virtual machine, that could significantly degrade performance, based on my experience. Other factors that may affect performance include themes and plugins. And if you're utilizing custom CSS snippets, it is advisable to avoid using the `:has()` selector, as it is known to cause performance issues.

Hope this helps!

**Comment by mustakshif** [comment]
Oh..I initially thought you were using a virtual machine on macOS because the mouse cursor in your screen recording resembled the macOS cursor, and your Obsidian instance was also running on macOS.

Have you tried using SiYuan directly on macOS? I'm not certain if animation performance is affected by the operating system. Unfortunately, I don't have a Windows device available for testing, but I have experienced animation lagging when running Windows in a Parallels virtual machine. That's where my previous assumption about virtual machines impacting performance stemmed from.

**Comment by MrIntellectX** [comment]
Unfortunately, I don't have a macOS device at the moment 😅, but I've tested SiYuan on my friend's MacBook with M1 chip, with all those snippets, themes, & plugins, and it was as smooth as what you've experienced. I believe the issue might be specific to Windows machines, especially older ones like mine, and I totally get your assumption. Yeah, Windows on Parallels usually sucks.

**Comment by mustakshif** [comment]
It seems like the only solution for now might be to use the default theme. Haha, not the most exciting option, but at least it should help mitigate the lagging issues.

Thanks for clarifying and letting me know about the potential performance issues of Asri on real Windows devices. I appreciate you taking the time to provide that feedback. I'll pay closer attention to Windows performance and optimization during future development of Asri. Feel free to reach out if you encounter any other issues or have additional suggestions.

**Comment by MrIntellectX** [comment]
Thanks for your understanding! I'll keep you posted on any updates regarding the Asri theme. By the way, I really love this theme, great work!

**Comment by mustakshif** [comment]
Hey, sorry to bug you. Are you still using Asri and is this issue still bothering you? 😂

I was testing and found out that SiYuan on Mac has "GPU raster" on by default, while it's off on Windows. Maybe you could try enabling it to fully use your GPU. Just right-click on SiYuan's shortcut, click on `properties`, and add ` --enable-gpu-rasterization` (with a space) at the end of the "Target" box.

<img width="417" alt="screenshot" src="https://github.com/user-attachments/assets/b75a3384-8d30-4f0d-9b4c-868dff80abf0">

It didn’t make much of a change for me on SiYuan in Parallels Windows, but it might work for you, I don't know. Just thought I'd mention it.
