### ISSUE TITLE
全屏状态下插入表情界面过窄

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#30]
如下图，全屏状态下插入表情的界面过窄，非全屏下无此问题。PS:有添加过自定义表情，就是自己的png表情放入思源的表情目录下。
![image](https://github.com/mustakshif/Asri/assets/63196026/31483ef1-edd0-434c-a9cb-1f3dbaac98fd)
![image](https://github.com/mustakshif/Asri/assets/63196026/ebfeecfa-5768-4fda-8247-5f4a0410b75d)

**Comment by 5kyfkr** [comment]
已测试只要放入了自定义表情就会这样
![image](https://github.com/mustakshif/Asri/assets/63196026/50f706e2-b478-4a49-bbe0-c0684d874979)

**Comment by mustakshif** [comment]
感谢反馈。找到原因了，下个版本更新。版本更新前可以先用这段css代码顶着：

@media screen and (min-width: 1292px) {
    .protyle-hint.hint--menu > .emojis {
        min-width: 50vw;
      }
}
