### ISSUE TITLE
收集箱点击文章后缺少返回箭头

### ISSUE THREAD

**Issue by mozhux** [mustakshif/Asri#32]
如题
![image](https://github.com/mustakshif/Asri/assets/46953371/7f7bb46f-93bd-4668-b636-2e4a12ffc5f5)
![image](https://github.com/mustakshif/Asri/assets/46953371/580c16b8-a971-4570-9cbf-1ba27e191d46)

**Comment by mustakshif** [comment]
感谢反馈，已在 #31 解决，今天晚些时候更新版本
