### ISSUE TITLE
主题3.0版本手机端显示不正常

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#34]
如题，手机端卸载了思源重装（不需要重装直接升级应该也能复现），然后更新到3.0主题后，左右菜单栏和设置选项的背景丢失，数据库的表格线无法显示，用回上一版本就正常
![Screenshot_20240403_073433_org b3log siyuan](https://github.com/mustakshif/Asri/assets/63196026/2fcd59d2-a1fd-4408-8ff8-036f09e275e3)
![Screenshot_20240403_073446_org b3log siyuan](https://github.com/mustakshif/Asri/assets/63196026/5bb3d9b2-272e-43e6-99d5-6811b6f4216d)
![Screenshot_20240403_073501_org b3log siyuan](https://github.com/mustakshif/Asri/assets/63196026/c8ff7614-0cae-4608-adbc-3cd335403238)

**Comment by mustakshif** [comment]
是思源新版本改了页面吗？我没升级手机端到最新版本，用3.0主题显示是正常的

![Screenshot_2024-04-03-08-16-37-726_org.b3log.siyuan.jpg](https://github.com/mustakshif/Asri/assets/100056458/59fcf148-6c16-4821-88c0-be1656ce80df)

![Screenshot_2024-04-03-08-16-47-454_org.b3log.siyuan.jpg](https://github.com/mustakshif/Asri/assets/100056458/c2e857f4-8de6-48b3-a43e-167734262102)

其他主题能正常显示吗？要不先换用其他主题吧，这确实影响使用了

**Comment by mustakshif** [comment]
我升级到思源最新版也是能正常显示的

![Screenshot_2024-04-03-08-25-55-407_org.b3log.siyuan.jpg](https://github.com/mustakshif/Asri/assets/100056458/c44ca5b5-bebd-4810-be69-b0ee22b6bac4)

你的情况可能是主题js报错了，可以下载一个开发者工具，用它的vconsole看看有什么主题相关的报错吗

![Screenshot_2024-04-03-08-28-57-841_org.b3log.siyuan-edit.jpg](https://github.com/mustakshif/Asri/assets/100056458/03668953-b8f4-4292-8e90-858324af4f02)

![Screenshot_2024-04-03-08-29-19-316_org.b3log.siyuan.jpg](https://github.com/mustakshif/Asri/assets/100056458/5e2ea3e7-9d63-41a5-b633-b8863e90f99d)

**Comment by 5kyfkr** [comment]
这是报错，我等下关了任务插件试试
![Screenshot_20240403_083924_org b3log siyuan](https://github.com/mustakshif/Asri/assets/63196026/4acdf40e-6bcc-4268-b849-02a9c2002313)
![Screenshot_20240403_083928_org b3log siyuan](https://github.com/mustakshif/Asri/assets/63196026/c3c1997c-48a5-43af-8b91-67d213e8165c)

**Comment by 5kyfkr** [comment]
关了报错的插件还是会剩下一个报错，应该是主题的错误了吧
![Screenshot_20240403_084621_org b3log siyuan](https://github.com/mustakshif/Asri/assets/63196026/d929aeb9-a975-4c23-a0ee-0250a3a36516)
![Screenshot_20240403_084628_org b3log siyuan](https://github.com/mustakshif/Asri/assets/63196026/c5ba417b-a124-43a8-9110-38709febdea0)

**Comment by mustakshif** [comment]
嗯看到了，感谢。稍后尝试修复

**Comment by mustakshif** [comment]
集市主题包已经换源，麻烦删除重下看看是否还有显示异常的问题呢

**Comment by 5kyfkr** [comment]
> 集市主题包已经换源，麻烦删除重下看看是否还有显示异常的问题呢

是这个吗，我试了还是没修复
![image](https://github.com/mustakshif/Asri/assets/63196026/bd7ec5b9-8e57-4012-8440-8cee4d9660bb)

**Comment by mustakshif** [comment]
对的，手机端上删除重下还是报错吗

**Comment by 5kyfkr** [comment]
> 对的，手机端上删除重下还是报错吗

主题没报错了，但是显示还是有问题

**Comment by 5kyfkr** [comment]
主题除了主题文件夹不会有其他地方还有残留的东西了吧？

**Comment by mustakshif** [comment]
emmm 可能是手机浏览器内核不支持新的颜色格式。
可以在手机上下载个Chrome试一下吗，如果还不行那就得在手机上禁用新特性了🤦‍♂️

**Comment by mustakshif** [comment]
> 主题除了主题文件夹不会有其他地方还有残留的东西了吧？但是v2.1.16和以前的版本又没问题。我是3.0.6装了有问题然后卸载重装了思源，然后用3.0的主题就出现这个问题了

应该不会是这个原因。主题新版本采用了新的色彩空间来表示颜色，可能还没得到广泛支持

**Comment by 5kyfkr** [comment]
> emmm 可能是手机浏览器内核不支持新的颜色格式。 可以在手机上下载个Chrome试一下吗，如果还不行那就得在手机上禁用新特性了🤦‍♂️

我用手机的edge浏览器打开网页端和电脑上看没什么区别，看着也没问题，就是apk里面才有问题

**Comment by 5kyfkr** [comment]
> > 主题除了主题文件夹不会有其他地方还有残留的东西了吧？但是v2.1.16和以前的版本又没问题。我是3.0.6装了有问题然后卸载重装了思源，然后用3.0的主题就出现这个问题了
> 
> 应该不会是这个原因。主题新版本采用了新的色彩空间来表示颜色，可能还没得到广泛支持

记得D大说过apk是用webview实现的，会不会webview不行

**Comment by mustakshif** [comment]
可能是手机webview版本太低hhh

**Comment by mustakshif** [comment]
社区有人反馈pad也显示异常了，我得先在这些设备上禁用新特性了

**Comment by 5kyfkr** [comment]
> 可能是手机webview版本太低hhh

有可能，毕竟华为不怎么对安卓上心了，我是p50安卓12

**Comment by 5kyfkr** [comment]
> 社区有人反馈pad也显示异常了，我得先在这些设备上禁用新特性了

还是禁用新特性吧，主背景和边栏配色其实我是用自己的CSS的
`:root[data-theme-mode=light] {
--b3-theme-on-background: rgb(0,0,0);
--b3-theme-on-surface: rgb(30,30,30);
--b3-theme-background: rgb(255, 251, 248);
--b3-toolbar-blur-background: rgb(47,54,61);
}
:root[data-theme-mode=dark] {
--b3-theme-on-background: rgb(220,220,220);
--b3-theme-background: rgb(43,59,70);
--b3-theme-surface: rgb(28,35,40);
--b3-toolbar-blur-background: rgb(47,54,61);
}`

**Comment by mustakshif** [comment]
嗯嗯 抱歉占用你的时间测试了，我稍后再换源

**Comment by 5kyfkr** [comment]
> 嗯嗯 抱歉占用你的时间测试了，我稍后再换源

没事，小问题

**Comment by 5kyfkr** [comment]
测试了新上传的已经没问题了

**Comment by mustakshif** [comment]
感谢
