### ISSUE TITLE
KNote插件排版兼容

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#36]
如下图，是knote插件在默认主题下的样子
![image](https://github.com/mustakshif/Asri/assets/63196026/d3680535-98b3-488d-a3bc-a6935c3e07cb)
asri下顶栏按钮无法点击，元素排版错位，希望修复
![image](https://github.com/mustakshif/Asri/assets/63196026/3cab615f-7f99-411c-aa0f-0bdb77ca1d5e)

**Comment by mustakshif** [comment]
感谢反馈，稍后修复。是因为这个插件顶栏元素的id和思源顶栏的id重合了，应用到思源顶栏的样式也会同样应用到插件的顶栏，我觉得可以提醒下插件开发者，因为不止我的主题调整了思源的顶栏样式

**Comment by 5kyfkr** [comment]
> 感谢反馈，稍后修复。是因为插件的顶栏元素和思源窗口顶栏的id和类名都重合了，应用到思源顶栏的样式也会同样应用到插件的顶栏，我觉得可以提醒下插件开发者，因为不止我的主题调整了思源的顶栏样式

@suka233  大佬可以看看
