### ISSUE TITLE
引述块的上下边框是否过于宽了？

### ISSUE THREAD

**Issue by pakeh2866** [mustakshif/Asri#38]
![image](https://github.com/mustakshif/Asri/assets/5708881/1f418e65-ae59-45e9-a0b2-f20eb32bbe4e)

**Comment by mustakshif** [comment]
感谢反馈，下个版本调整一下

**Comment by Jiangshuon** [comment]
大佬，手机上引用的左右间距是不是也宽了点，手机上空间本来就挺小，希望能紧凑点。感觉lightblue的间距比较合适，在手机上

![Screenshot_20240409165641](assets/Screenshot_20240409165641-20240409165658-ilylwmi.jpg)


![c3c415434bee3f9cec6ee8c565ee385](https://github.com/mustakshif/Asri/assets/67137548/e35c32de-cc17-4cd3-abd6-94ec194e9881)

**Comment by mustakshif** [comment]
> 大佬，手机上引用的左右间距是不是也宽了点，手机上空间本来就挺小，希望能紧凑点。感觉lightblue的间距比较合适，在手机上

感谢提议，后面我测试一下。移动端其实我没有怎么适配，因为个人不常用。后面如果有其他建议也欢迎提出:)

**Comment by Jiangshuon** [comment]
好的，我刚更新到最新版本，发现移动端不太对，又提了个issue
