### ISSUE TITLE
是否可以支持多级列表区别编号

### ISSUE THREAD

**Issue by liuxingar** [mustakshif/Asri#40]

**Comment by mustakshif** [comment]
感谢提议。我个人觉得缩进区分已经足够了；其次区分编号的格式以什么为标准、是否适合所有人，也需要考虑。以后可能会做成主题的自定义配置项，不过时间不确定。

如果真的需要这个特性的话，可以先考虑复制其他主题中的相关 css 代码作为自定义代码
