### ISSUE TITLE
关系图的搜索框没有覆盖住后面的按钮

### ISSUE THREAD

**Issue by LoneFireBlossom** [mustakshif/Asri#41]
如图：
<img width="457" alt="image" src="https://github.com/mustakshif/Asri/assets/50087596/10d7b8c1-fa7d-4803-a823-df2c66c713f6">
这些按钮干扰视线。

默认主题里打开这个搜索框之后，下面的按钮就都被覆盖住了，我觉得这样更好。

**Comment by mustakshif** [comment]
感谢反馈，下个版本修复
