### ISSUE TITLE
与自定义CSS片段有冲突，标题段间距问题……？

### ISSUE THREAD

**Issue by LoneFireBlossom** [mustakshif/Asri#49]
这个问题不好一句话概括。
首先，我用了这样一段CSS片段来调整标题的字号和间距：

```
.protyle-wysiwyg .h1,
.protyle-wysiwyg [data-node-id].li > .protyle-action ~ .h1 {
    font-size: 1.30em !important;
    margin-bottom: 0.25em !important;
    margin-top: 0.25em !important
}

.protyle-wysiwyg .h2,
.protyle-wysiwyg [data-node-id].li > .protyle-action ~ .h2 {
    font-size: 1.25em !important;
    margin-bottom: 0.25em !important;
    margin-top: 0.25em !important
}

.protyle-wysiwyg .h3,
.protyle-wysiwyg [data-node-id].li > .protyle-action ~ .h3 {
    font-size: 1.20em !important;
    margin-bottom: 0.25em !important;
    margin-top: 0.25em !important
}

.protyle-wysiwyg .h4,
.protyle-wysiwyg [data-node-id].li > .protyle-action ~ .h4 {
    font-size: 1.15em !important;
    margin-bottom: 0.25em !important;
    margin-top: 0.25em !important
}

.protyle-wysiwyg .h5,
.protyle-wysiwyg [data-node-id].li > .protyle-action ~ .h5 {
    font-size: 1.10em !important;
    margin-bottom: 0.25em !important;
    margin-top: 0.25em !important
}

.protyle-wysiwyg .h6,
.protyle-wysiwyg [data-node-id].li > .protyle-action ~ .h6 {
    font-size: 1.05em !important;
    margin-bottom: 0.25em !important;
    margin-top: 0.25em !important
}
```

显然是标题级别越低字体就越小，所以占地方就越小。这在默认主题下就是如此。
但是在asri主题下，从一级标题转换到二级标题的时候会发现占地方变大了（宽度变宽了），不知道是何原因？是CSS片段有冲突么？求教，示例见下面的视频

https://github.com/mustakshif/Asri/assets/50087596/cd1a2488-c631-467d-8a3d-562fa95dfa3e

**Comment by mustakshif** [comment]
```css
.protyle-wysiwyg .h1, .protyle-wysiwyg h1 {
    padding: .3em 4px;
}
```

代码片段添加这个

**Comment by LoneFireBlossom** [comment]
> ```css
> .protyle-wysiwyg .h1, .protyle-wysiwyg h1 {
>     padding: .3em 4px;
> }
> ```
> 
> 代码片段添加这个

添加这个CSS，会导致列表里的标题块前面的编号没法对齐😂
<img width="326" alt="image" src="https://github.com/mustakshif/Asri/assets/50087596/57d3039d-a7e8-433b-8656-53e510c71cde">

**Comment by mustakshif** [comment]
<img width="324" alt="image" src="https://github.com/mustakshif/Asri/assets/100056458/3ac8b7ba-9b1a-4ed4-8ca7-8075b7545796">

我这里正常的

> ```css
> .protyle-wysiwyg .h1, .protyle-wysiwyg h1 {
>     padding: .3em 4px;
> }
> ```

你是不是在这里加了 !important 之类的，或者对padding做了其他修改？正常情况下列表中的标题块的上下padding为0，这是默认自带的样式，不会出现图中那样的空白

<img width="345" alt="截屏2024-04-25 20 02 36" src="https://github.com/mustakshif/Asri/assets/100056458/a9619197-d229-4a61-9336-288ba3a1e8c9">

**Comment by LoneFireBlossom** [comment]
我错了，我把`    padding: .3em 4px;`这个直接加到我1楼代码的括号里了，以为前缀一样……对不起
