### ISSUE TITLE
调整文档的文件名字号后，块标位置没有跟着对齐

### ISSUE THREAD

**Issue by LoneFireBlossom** [mustakshif/Asri#50]
使用如下CSS片段：

```
.protyle-title__input {
font-size: 1.45em !important;
}
```

如图所示：
<img width="448" alt="image" src="https://github.com/mustakshif/Asri/assets/50087596/93064c00-0172-44fe-8fb5-3808fa8e3715">

可以看到块标明显与字没有对齐。
Asri上个版本没有这个问题的，更新以后出现了这个问题。

**Comment by LoneFireBlossom** [comment]
感谢，解决了。
不过我看之前的issue是为了应对其它插件的影响而做出的修改，这样反倒会影响默认场景下的情况……（只是修改标题字号应该也算默认场景吧），感觉是不是应该让插件那边修改，而不是主题这边修改

**Comment by mustakshif** [comment]
有道理，不过那个插件改块标定位的方式也只是以默认主题为准的，其他主题如果改了文档标题样式往往也对不齐，所以我只能按照我的主题样式进行计算方式上的适配，不管用不用那个插件、编辑器字号设置为多少都能居中，但确实无法照顾到单独修改标题字号的情况
