### ISSUE TITLE
面包屑半透明显示

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#51]
大佬，有没有可能实现面包屑半透明或全透明显示，感觉面包屑栏占了挺多顶部空间，一般中间都是空的，我试了css好像实现不了半透明
![image](https://github.com/mustakshif/Asri/assets/63196026/d7a6eb1a-a5a8-40a5-89ee-47712040bacd)

这个是彻底隐藏面包屑的代码：
.protyle-breadcrumb {
	display:none;
 }
这个是尝试半透明的，但是只有文字变半透明了，背景还是一样
.protyle-breadcrumb {
	opacity: 0.5;
 }
要是能自动隐藏，只有滑动页面到顶端才显示，应该也能解决问题

**Comment by mustakshif** [comment]
可以是可以不过会有小问题，我以前试过，比如可能导致向上拖移块时无法在顶部触发自动滚动、右侧块进度条不会自动刷新

总体思路是把面包屑的margin-bottom设为负数，背景色改成透明色

**Comment by 5kyfkr** [comment]
> 可以是可以不过会有小问题，我以前试过，比如可能导致向上拖移块时无法在顶部触发自动滚动、右侧块进度条不会自动刷新
> 
> 总体思路是把面包屑的margin-bottom设为负数，背景色改成透明色

试了确实有这些问题，不折腾了
