### ISSUE TITLE
3.0.12 dev3文档标签位置偏移

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#54]
如题，最新开发版本中如下图，文档标签在最右侧，应和默认主题一样在标题上方
![image](https://github.com/mustakshif/Asri/assets/63196026/f3272502-b09d-41b3-af04-cc0cf80dc709)
默认主题如下：
![image](https://github.com/mustakshif/Asri/assets/63196026/24444166-64da-4f46-a1ca-6442dd826f29)

**Comment by 5kyfkr** [comment]
另外感觉好像如果没有标签空的位置太多了，我去那边提提建议改回图标旁边好点
![image](https://github.com/mustakshif/Asri/assets/63196026/7df80688-679b-4828-8b5d-32f7e6dd7c14)

**Comment by mustakshif** [comment]
我看了下新版本这里改动比较多，提前修改的话可能破坏当前版本的布局，等3.0.12正式版发布过后再修复。感谢反馈
