### ISSUE TITLE
iPadOS端思源在设置-集市-图标页面下出现侧边栏重叠

### ISSUE THREAD

**Issue by LoneFireBlossom** [mustakshif/Asri#55]
如图所示，刚安装的asri，思源，鼠标在屏幕上移动时就会变成这样
<img width="1366" alt="image" src="https://github.com/mustakshif/Asri/assets/50087596/572aefb6-006e-494c-bacc-7564010e0cd6">

默认主题下没有此问题

iPadOS 17.3.1

**Comment by mustakshif** [comment]
感谢反馈，后面会尝试修复
