### ISSUE TITLE
Minor Conflict with Map Display from Custom-Block

### ISSUE THREAD

**Issue by hep-cogth** [mustakshif/Asri#56]
Support of Map Display comes with Custom-Block.

Problem
![image](https://github.com/mustakshif/Asri/assets/88515612/19cc6b1e-6ff2-4524-9cc4-a9eda2ff1b77)

Reproducible *only with pretty big font size*; you can debug with quick adjust font size. (to operate, press control and scroll the wheel)

IMHO, it's due to some **hardcoded CSS styles like `height` and `width`** that caused the similar issues; so would consider make the theme more flexible, which it probably a major revision, when opportunity arises and time permits?

**Comment by mustakshif** [comment]
Did you mean this plugin?
<img width="399" alt="image" src="https://github.com/mustakshif/Asri/assets/100056458/65d4156d-585d-41bd-a826-9b2e03ed4e01">

I tested the map list view and everything appears as expected on my end. Please check for any conflicting CSS snippets that might be affecting the display
<img width="335" alt="截屏2024-04-29 18 00 58" src="https://github.com/mustakshif/Asri/assets/100056458/394e6bb0-a771-466f-878e-e5bc374c8d17">

**Comment by mustakshif** [comment]
Thank you for clarifying the problem description.

> Reproducible _only with pretty big font size_; you can debug with quick adjust font size. (to operate, press control and scroll the wheel)

Yes, the problem appears when I enlarge the font size in my editor.

But since this issue also occurs with the default theme, I think it's best to report this to the plugin developer. They will likely be more familiar with the overall map view structure.

**Comment by mustakshif** [comment]
> IMHO, it's due to some **hardcoded CSS styles like `height` and `width`** that caused the similar issues; so would consider make the theme more flexible, which it probably a major revision, when opportunity arises and time permits?

Also, I'm with you on this. It's true that at times, I used hardcoded styles without testing them across different font sizes, especially during the early stages of developing for Asri. So, if you notice any related issues, please don't hesitate to report them.
