### ISSUE TITLE
希望表格支持横向滚动条

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#62]
如题，现在在移动端或编辑窗口较窄的情况下，表格会被拉长很多，默认主题是有横向滚动条的，希望也能支持。
![image](https://github.com/mustakshif/Asri/assets/63196026/887fe133-ed94-4f91-bb84-584d0ba7e29e)

图中表格在以下链接开头可以复制
https://ld246.com/article/1710832318646

**Comment by mustakshif** [comment]
电脑端会倾向于避免触发横向滚动，如有需要可以手动启用一下表格的[全宽显示](https://github.com/mustakshif/Asri/blob/main/README_zh_CN.md#1-afwd%E5%85%A8%E5%AE%BD%E6%98%BE%E7%A4%BAasri-full-width-display)；移动端下个版本优化。感谢反馈～

**Comment by 5kyfkr** [comment]
> 电脑端会倾向于避免触发横向滚动，如有需要可以手动启用一下表格的[全宽显示](https://github.com/mustakshif/Asri/blob/main/README_zh_CN.md#1-afwd%E5%85%A8%E5%AE%BD%E6%98%BE%E7%A4%BAasri-full-width-display)；移动端下个版本优化。感谢反馈～

是滴，主要是移动端很难绷

**Comment by mustakshif** [comment]
已修复。可以下载最新 theme.css 替换本地文件
