### ISSUE TITLE
大纲面板标题等级标记未居中

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#65]
如下图，标题等级标记都偏向左上角了
![image](https://github.com/mustakshif/Asri/assets/63196026/0202deb8-ed37-41f9-befe-235f52e9c0dd)

**Comment by mustakshif** [comment]
<img width="214" alt="截屏2024-05-17 11 50 20" src="https://github.com/mustakshif/Asri/assets/100056458/e4d877fb-5dd0-4a05-bc1d-fecaf66b7ecc">

我这里没问题，这是 Windows 上截的。会不会是代码片段的影响

**Comment by 5kyfkr** [comment]
是文档树自定义插件，调了文档树字体大小就这样了，我看看有没办法改图标的css

**Comment by mustakshif** [comment]
好的 我等会也看看

**Comment by mustakshif** [comment]
> ![image](https://private-user-images.githubusercontent.com/63196026/331454541-d39a8da1-adcd-46e6-afc0-9ed38d0eb3b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTkyMDAsIm5iZiI6MTcxNTkxODkwMCwicGF0aCI6Ii82MzE5NjAyNi8zMzE0NTQ1NDEtZDM5YThkYTEtYWRjZC00NmU2LWFmYzAtOWVkMzhkMGViM2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0MDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjg2YTRmZDUzMjkzYTdkYWUxODMwMTQ0N2MzNDEwMGY4MmM5OTAyNGY0MTkyOTVlZWM5YjY5OGZlZGU2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.54c1kWM33_CyjqzD_DfViPxSzIzCmQBs4eaIt-S5L-4) 是文档树自定义插件，调了文档树字体大小和行高就这样了，我看看有没办法改图标的css

这些选项好像对我的主题没有影响，我开了也没效果

**Comment by 5kyfkr** [comment]
> 这些选项好像对我的主题没有影响，我开了也没效果

这个插件要重启思源才能应用效果

**Comment by 5kyfkr** [comment]
开了这个插件在默认主题里也不会偏移
![image](https://github.com/mustakshif/Asri/assets/63196026/b2d3a8ae-57bf-437f-a617-cffff16ce68e)

**Comment by 5kyfkr** [comment]
我现在插件里调的字体大小16，行高18

**Comment by mustakshif** [comment]
修复了，你下载最新 css 看下

**Comment by 5kyfkr** [comment]
![image](https://github.com/mustakshif/Asri/assets/63196026/06939819-0b81-4285-9962-0c703299b5e5)
似乎还有一点点偏下

**Comment by mustakshif** [comment]
<img width="258" alt="image" src="https://github.com/mustakshif/Asri/assets/100056458/ff88fa9a-00d1-4b52-a34e-fac15b977946">

> 我现在插件里调的字体大小16，行高18

我跟你用了一样的配置，看起来是正常的

**Comment by 5kyfkr** [comment]
那应该是字体问题了，用微软雅黑就正常，鸿蒙黑体可能会高一点
![image](https://github.com/mustakshif/Asri/assets/63196026/19e568f8-3220-400e-b644-61ecb3c32fe4)

**Comment by mustakshif** [comment]
body.body--win32 .sy__outline .b3-list-item[data-type=NodeHeading] {
    line-height: 1.4;
}

可以试试这个，可以微调一下数值；不过每次调整字号行高都得再次调整

**Comment by 5kyfkr** [comment]
> .sy__outline .b3-list-item[data-type=NodeHeading] .b3-list-item__text::before { transform: translateY(-.08em); }
> 
> 这样应该可以了，字号大小无论多少都能保持居中

厉害了我的佬
![image](https://github.com/mustakshif/Asri/assets/63196026/0ebbe7f6-8a69-4b57-8640-4a6b2a7db8e8)

**Comment by 5kyfkr** [comment]
![image](https://github.com/mustakshif/Asri/assets/63196026/d0959e92-4df0-4f34-af80-1002ca433df5)
大佬，这两个图标有没办法用css隐藏，移除按钮插件那边我也提了这个需求

**Comment by mustakshif** [comment]
> 这两个图标有没办法用css隐藏

.layout-tab-bar--readonly {display: none}

**Comment by 5kyfkr** [comment]
> > 这两个图标有没办法用css隐藏
> 
> .layout-tab-bar--readonly {display: none}

神了，巨佬

**Comment by mustakshif** [comment]
> 要是能把主菜单的名字改成头像那就更强了，类似浏览器

感觉要靠思源官方了，比如说在账号页面添加一个顶栏显示用户头像的开关

**Comment by 5kyfkr** [comment]
> > 要是能把主菜单的名字改成头像那就更强了，类似浏览器
> 
> 感觉要靠思源官方了，比如说在账号页面添加一个顶栏显示用户头像的开关

不过我刚才细想了也不太好，现在的实际是工作空间的名字，删了换成头像就没法区分了，如果又有头像又有名称又有点占位置了，还是现在这样就可以了

**Comment by mustakshif** [comment]
哈哈 是呢，加了用处也不大
