### ISSUE TITLE
如何在asri模式中给自己常用的一些网站加上favicon？

### ISSUE THREAD

**Issue by jumpoutofworld** [mustakshif/Asri#66]
参考这里的方法：
[网站超链接图标在思源笔记中如何展现 - 链滴](https://ld246.com/article/1633499156617)
没有找到icon对应的目录

**Comment by mustakshif** [comment]
Asri 没有原生支持这个功能。有试过这个插件吗，应该可以满足你的需要：

<img width="393" alt="image" src="https://github.com/mustakshif/Asri/assets/100056458/2fd22b51-8336-4286-bbda-58e9a5c41213">
