### ISSUE TITLE
展开侧边栏后挤占标签页空间

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#67]
![image](https://github.com/mustakshif/Asri/assets/63196026/510bc497-121a-4cc9-9f27-8c29a44824e2)
如图，顶栏标签区域宽度能不能不被侧栏影响呢

**Comment by 5kyfkr** [comment]
感觉有点困难可能，原生设计就是这样的，看大佬了，不行也没事，我自动隐藏侧栏
![image](https://github.com/mustakshif/Asri/assets/63196026/6926be6d-8d39-48b0-a97e-87a1a312b638)

**Comment by mustakshif** [comment]
暂时不考虑更改了。Asri 是利用了默认主题的这个特点的，让页签撑满是另一种风格，得重新设计

**Comment by 5kyfkr** [comment]
> 暂时不考虑更改了。Asri 是利用了默认主题的这个特点的，让页签撑满是另一种风格，得重新设计
> 
> > 如图，顶栏标签区域宽度能不能不被侧栏影响呢
> 
> 得用 js 计算宽度差，然后将页签容器的左右 margin 设为相应的负值

那就算了吧，有点麻烦了应该
