### ISSUE TITLE
knote插件影响/菜单展示界面

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#68]
如下图，输入斜杠/后界面被knote后面的callout样式拉长了，大佬看看有没办法优化下，应该是只有最后一列需要拉宽，前面几列宽度不变
![image](https://github.com/mustakshif/Asri/assets/63196026/84d4f227-aef3-4107-8804-71ce8f8793b7)

**Comment by mustakshif** [comment]
OK 了。

> 应该是只有最后一列需要拉宽，前面几列宽度不变

这个分栏布局没有办法单独调整某列的宽度，只能限制列宽了

**Comment by 5kyfkr** [comment]
> OK 了。
> 
> > 应该是只有最后一列需要拉宽，前面几列宽度不变
> 
> 这个分栏布局没有办法单独调整某列的宽度，只能限制列宽了

好滴，没问题
