### ISSUE TITLE
全黑自定义主题色无法应用

### ISSUE THREAD

**Issue by EberhardLin** [mustakshif/Asri#73]
如图，字体是粉色
![image](https://github.com/mustakshif/Asri/assets/98400319/9cef3137-2559-43cd-bb80-96bd1b6a6258)

**Comment by mustakshif** [comment]
强调文本必须与非强调文本用饱和度区分开来，暂不支持强调色为纯灰度色，这是特性；纯灰色下强调色呈现粉色，这是色彩系统算法导致的。

如果希望强调色是其他颜色（如蓝色），同时保持其他颜色视觉上是灰色，只能把主题色设为其他颜色的低亮度或低饱和度色，而不是纯黑：

<img width="303" alt="截屏2024-05-31 12 13 04" src="https://github.com/mustakshif/Asri/assets/100056458/e22a1ce5-7ad3-4a22-9d15-5e961d8d984f">

<img width="311" alt="截屏2024-05-31 12 09 34" src="https://github.com/mustakshif/Asri/assets/100056458/899f6239-95f4-475e-82ae-6c6dcdd8277d">

**Comment by EberhardLin** [comment]
> 强调文本必须与非强调文本用饱和度区分开来，暂不支持强调色为纯灰度色，这是特性；纯灰色下强调色呈现粉色，这是色彩系统算法导致的。
> 
> 如果希望强调色是其他颜色（如蓝色），同时保持其他颜色视觉上是灰色，只能把主题色设为其他颜色的低亮度或低饱和度色，而不是纯黑：
> 
> <img alt="截屏2024-05-31 12 13 04" width="303" src="https://private-user-images.githubusercontent.com/100056458/335442910-e22a1ce5-7ad3-4a22-9d15-5e961d8d984f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjkyNjksIm5iZiI6MTcxNzEyODk2OSwicGF0aCI6Ii8xMDAwNTY0NTgvMzM1NDQyOTEwLWUyMmExY2U1LTdhZDMtNGEyMi05ZDE1LTVlOTYxZDhkOTg0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNDE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTU1YTU3ODgzYTMwNDJmZGI4MzFiNzQ1YjlmN2M0ZWFjNzMzNDI5ZDM0NzgxNGRkODc1MzVmNDBhOGY3NTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TbQyH-SsNPSgvIrQhYyjaLfYJ866HLTU16Zvlv1JJIE"> <img alt="截屏2024-05-31 12 09 34" width="311" src="https://private-user-images.githubusercontent.com/100056458/335442989-899f6239-95f4-475e-82ae-6c6dcdd8277d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjkyNjksIm5iZiI6MTcxNzEyODk2OSwicGF0aCI6Ii8xMDAwNTY0NTgvMzM1NDQyOTg5LTg5OWY2MjM5LTk1ZjQtNDc1ZS04MmFlLTZjNmRjZGQ4Mjc3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNDE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjE0MTY2MTY0NzZmMzEwMjBkZWExMDk0NDE4N2UxNWI1NGY3NmU1YzA4ZDBkNWQyYWY1Nzg5MDIwYWE2ZGRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s4VP13noDQmoqMxYUb9BXn-y2kkM7UNB-1puV0T7wBk">

明白了，因为技术上我也不太懂，提一个小白一点的建议供您考虑下哈：以后有可能针对这点优化下吗，例如强调文本为加粗黑， 或者非强调文本为深灰色（强调文本为非加粗纯黑）。因为我色彩上比较喜欢黑-灰-白三色，例如非强调文本为正常纯黑，强调文本为加粗纯黑，界面的部分背景色为灰色（例如现在的侧边栏），主题背景色为白色这种。
个人想法，供您考虑，主题本身很优秀，算是我自己觉得的可以增加的一个点。

**Comment by mustakshif** [comment]
强调色不止用到文字上，还有图标和部分组件，没法简单加粗。暂时不会改了。感谢提议。

**Comment by EberhardLin** [comment]
> 强调色不止用到文字上，还有图标和部分组件，没法简单加粗。暂时不会改了。感谢提议。

ok
