### ISSUE TITLE
钉住侧边栏的情况下，会遮盖顶栏

### ISSUE THREAD

**Issue by EberhardLin** [mustakshif/Asri#74]
没钉住侧边栏时：
![image](https://github.com/mustakshif/Asri/assets/98400319/23246d98-aed9-424f-9e6b-71249f878ca3)
钉住侧边栏时，顶栏被遮盖：
![image](https://github.com/mustakshif/Asri/assets/98400319/6412b419-5f45-4a3f-aef1-18e6719e484d)
右侧也是同样：
![image](https://github.com/mustakshif/Asri/assets/98400319/61a29c96-332f-493b-af8a-24c7104aca10)
---
如果可以的话，可不可以考虑优化下这一点，视觉上和没钉住侧边栏统一下。
考虑考虑呗~

**Comment by mustakshif** [comment]
看图标状态，你的1图和2图反了吧，1图是钉住侧栏的状态，2图才是非钉住也就是浮动侧栏的状态。浮动侧栏情况下会撑满页面高度，覆盖顶栏一部分，获得最大显示高度，这是特性，毕竟浮动情况下只是需要的时候才呼出，鼠标移开后自动收回，不会总是占据页面内容

**Comment by EberhardLin** [comment]
> 看图标状态，你的1图和2图反了吧，1图是钉住侧栏的状态，2图才是非钉住也就是浮动侧栏的状态。浮动侧栏情况下会撑满页面高度，覆盖顶栏一部分，获得最大显示高度，这是特性，毕竟浮动情况下只是需要的时候才呼出，鼠标移开后自动收回，不会总是占据页面内容

不好意思哈，没注意，所以这点不能改吗，因为我总觉得浮动侧栏撑满页面高度好丑，不过也不是不能接受，所以上来提一嘴。

**Comment by mustakshif** [comment]
这个暂时不会改了
