### ISSUE TITLE
安卓Pad端异常

### ISSUE THREAD

**Issue by Soltus** [mustakshif/Asri#75]
右下角的元素跑到左上角了，在电脑上是正常的
![9f5a95d266a794e93e7ba22d18aff19c](https://github.com/mustakshif/Asri/assets/83791825/e7f03625-de82-4e08-bc61-7120052abf07)

**Comment by mustakshif** [comment]
感谢反馈。我手边没有安卓平板设备，但尝试修复了一下，麻烦下载一下 [theme.js](https://github.com/mustakshif/Asri/blob/main/theme.js) 替换本地主题文件夹下的同名文件，然后重进思源看是否还有问题

**Comment by mustakshif** [comment]
如果不方便的话，可以等明天更新主题后再看一下

**Comment by Soltus** [comment]
试了一下没有解决问题。我对右下角进行了魔改，应该是冲突了。

**Comment by Soltus** [comment]
但是桌面端没有问题，会不会是webview版本问题？平板系统不更新了，内核版本是99，桌面端早就110+了

**Comment by mustakshif** [comment]
应该是主题的原因，我在电脑上给 body 元素添加 body--mobile 类名就可以复现。可能是主题 js 设备判断没写好，把安卓平板当手机设备了。。可以给我看一下你的设备的 userAgent 信息吗

**Comment by Soltus** [comment]
body class="branch--Sillot body--desktop fn__flex-column body--mobile"
![16868654554631ab6d3e3001299781d8](https://github.com/mustakshif/Asri/assets/83791825/4fdc5672-a32b-4437-8f70-362d2be59c84)

**Comment by mustakshif** [comment]
<img width="1236" alt="image" src="https://github.com/mustakshif/Asri/assets/100056458/b6ad70ed-8f3a-4571-84fa-a555a01300d0">

我用你的 ua 按我最新的 js 写法测试了一下，设备判断是没问题的，可是为什么你的 body 上还是有 body--mobile 呢 😂。替换过程是否成功了呢，还是说其他的插件添加了这个类名

**Comment by Soltus** [comment]
你是通过 body--mobile 判断是手机端吗，通过 and not body--desktop 判断应该可以吧。我这里 body--mobile 就是移动端App的意思，平板手机都一样，伺服就不会有

**Comment by mustakshif** [comment]
我没有写 desktop 端的逻辑，因为默认就是，其他端的设备才需要判断一下，如果是移动设备主题 js 会添加一个 body--mobile 类名，平板端用的是浏览器 body--browser 类型

> 我这里 body--mobile 就是移动端App的意思，平板手机都一样，伺服就不会有

意思是这个 body--mobile 类名是你自己加上去的吗

**Comment by Soltus** [comment]
> 意思是这个 body--mobile 类名是你自己加上去的吗

应该没错

**Comment by mustakshif** [comment]
那好吧 我把主题添加的类名再添加一个 asri 前缀，避免潜在冲突

**Comment by Soltus** [comment]
🤍

**Comment by mustakshif** [comment]
改好了，麻烦替换下最新的 theme.css 和 theme.js 看看是否还有问题～

**Comment by Soltus** [comment]
![fa8d6ec90dc22d7b66b227146449ff29](https://github.com/mustakshif/Asri/assets/83791825/61c3dfc4-8b72-46d7-9217-5367edbb28e1)
