### ISSUE TITLE
There is something wrong with the style of the super block!

### ISSUE THREAD

**Issue by zczczcaaa** [mustakshif/Asri#79]
![image](https://github.com/mustakshif/Asri/assets/63695712/fd50b93b-16e9-43b0-a5c5-8b88b312c7bb)

**Comment by mustakshif** [comment]
Thank you for your feedback. Will try to fix that in the next update.

**Comment by mustakshif** [comment]
This issue has been fixed. You can download the latest [theme.css](https://github.com/mustakshif/Asri/blob/main/theme.css) and replace your local file to apply the update immediately on your device, or wait until next Monday to update via the SiYuan marketplace.
