### ISSUE TITLE
又无法导出为图片了

### ISSUE THREAD

**Issue by jl0476** [mustakshif/Asri#80]
![image](https://github.com/mustakshif/Asri/assets/5226690/971ebd48-a741-448d-86f6-223d7e834b9a)

![image](https://github.com/mustakshif/Asri/assets/5226690/0858c5ff-d8d5-4702-bf7b-4c9d747c0af2)

最新版，导出为图片又卡住了。

**Comment by mustakshif** [comment]
感谢反馈，已修复，可以下载最新 theme.css 替换本地文件即可正常导出
