### ISSUE TITLE
左右滑动移动端设置页会变成这样

### ISSUE THREAD

**Issue by Jiangshuon** [mustakshif/Asri#82]
![d6d7d6261da81487268310b38262b7b](https://github.com/mustakshif/Asri/assets/67137548/327f295c-e7f7-4795-b751-e0055892d743)

**Comment by Jiangshuon** [comment]
还有大佬，感觉这个页面负优化了，之前比现在好看多了，还有模糊效果！现在白色卡片感觉很割裂

![image](https://github.com/mustakshif/Asri/assets/67137548/ae6e45ee-a269-4815-849c-7267274a5387)

**Comment by mustakshif** [comment]
感谢反馈，这个页面还会持续优化的，下个版本回滚。

**Comment by mustakshif** [comment]
可以用最新 theme.css 替换本地文件，或者等下周更新
