### ISSUE TITLE
软件更新3.1.4版本后，主题代码块行号错位了

### ISSUE THREAD

**Issue by jakehu** [mustakshif/Asri#86]
相关issues：https://github.com/siyuan-note/siyuan/issues/12346
相关问题：https://ld246.com/article/1724737366356

**Comment by mustakshif** [comment]
感谢反馈，已经修复，马上发版

**Comment by gagmeng** [comment]
> 感谢反馈，已经修复，马上发版

这是因为主题的问题吗？不是因为思源本身失败导致的不适配？

**Comment by mustakshif** [comment]
> > 感谢反馈，已经修复，马上发版
> 
> 这是因为主题的问题吗？不是因为思源本身失败导致的不适配？

思源最新版本改动了相关部分的样式而已，说失败不至于吧
