### ISSUE TITLE
如图代码块行数大于100显示有问题

### ISSUE THREAD

**Issue by TopProgrammer** [mustakshif/Asri#87]
![image](https://github.com/user-attachments/assets/76bf347f-7457-4647-84ad-ae57e6bbd7fc)

**Comment by mustakshif** [comment]
这是Asri主题吗，我这边没问题。
主题和思源都更新到新版本了吗？

<img width="727" alt="image" src="https://github.com/user-attachments/assets/f594961c-65a3-495e-8fe5-3f1684c35717">
<img width="637" alt="image" src="https://github.com/user-attachments/assets/caa31cbb-2c16-4788-9000-fc89af716721">
