### ISSUE TITLE
右边分割线

### ISSUE THREAD

**Issue by zlxuan** [mustakshif/Asri#90]
右边分割线有点突破天际了吧，而且距离右边是不是有点宽了，有条能拉动的横线是做啥的？
不知是作者有意为之还是bug
![Snipaste_2024-09-13_18-24-00](https://github.com/user-attachments/assets/f273b420-baf1-4430-a758-f4421a538c81)

**Comment by mustakshif** [comment]
我从来没遇到过这种情况。可能是界面出问题了，到设置-外观-恢复默认窗口的重置试试看能否恢复正常

**Comment by mustakshif** [comment]
分割线到顶是已知问题，已经修复但是还没推送。可以手动下载主页的 [theme.css](https://github.com/mustakshif/Asri/blob/main/theme.css) 到本地，然后替换 Asri 主题目录中的同名文件即可；下方横向分割线可能是界面问题，按上面的方法应该能恢复

**Comment by 5kyfkr** [comment]
> 分割线到顶是已知问题，已经修复但是还没推送。可以手动下载主页的 [theme.css](https://github.com/mustakshif/Asri/blob/main/theme.css) 到本地，然后替换 Asri 主题目录中的同名文件即可；下方横向分割线可能是界面问题，按上面的方法应该能恢复

大神好久不见，刚上来想反馈这个问题就发现好了
