### ISSUE TITLE
点击文档大纲标题后自动切换成浏览模式

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#91]
如图，点击文章的大纲标题后，切换成了浏览模式
![动画](https://github.com/user-attachments/assets/84b6cfa3-33fa-4d98-a7b3-53e62c229759)

**Comment by mustakshif** [comment]
我没法复现诶，确定是主题的问题吗

**Comment by 5kyfkr** [comment]
> 我没法复现诶，确定是主题的问题吗

我新建了工作空间试的，应该是主题问题，要第一次打开思源，然后再打开文章就会这样

**Comment by 5kyfkr** [comment]
好像不是主题问题，默认主题也会这样，我去那边开个吧

**Comment by 5kyfkr** [comment]
https://github.com/siyuan-note/siyuan/issues/12500
提到这了
