### ISSUE TITLE
文档树点击区域优化

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#92]
https://ld246.com/article/1726984367643

大佬，如此贴，看看能不能把子文档展开的区域延伸到竖线区域，方便点击，贴内有一个回复好像直接改好了
![image](https://github.com/user-attachments/assets/c89d6c41-9799-4d64-bf4c-e9c9fde25c42)

**Comment by mustakshif** [comment]
感谢反馈。下个周我研究一下
