### ISSUE TITLE
win11 文档树的目录标题文字看不清，是灰色的，有办法调整吗？

### ISSUE THREAD

**Issue by ruaou** [mustakshif/Asri#95]
主题特别棒，就是文字这里有办法调整吗？看不清楚。好像被蒙了一层强调色的样子

**Comment by mustakshif** [comment]
感谢认可。这个样式已回滚修复，但还没发版，可以手动下载 [theme.css](https://github.com/mustakshif/Asri/blob/main/theme.css) 并替换本地主题文件夹下的同名文件即可
