### ISSUE TITLE
请问文档字体是不是渲染了，怎么自定义css还是原来字体

### ISSUE THREAD

**Issue by tianxia704** [mustakshif/Asri#98]
我觉得主题做的很好，尤其是顶栏合并这块，节省页面空间。
在切换主题时候发现字体显示不一样，粗了一点，是不是渲染了。比如和写味的和任我行。有没有css让字体不渲染，还是原来的？
arsi
<img width="708" alt="image" src="https://github.com/user-attachments/assets/17ece68f-870c-4bdf-838d-73d57ebd6414">

写味
<img width="744" alt="image" src="https://github.com/user-attachments/assets/df9cc190-5dbc-4891-8642-2c8ba36ce699">

任我行
<img width="765" alt="image" src="https://github.com/user-attachments/assets/83ae8365-8e6e-439a-a11b-81adce4be3d7">

**Comment by mustakshif** [comment]
你用的是什么CSS代码来自定义字体

**Comment by tianxia704** [comment]
您的邮件已收到，谢谢

**Comment by tianxia704** [comment]
> 你用的是什么CSS代码来自定义字体

没有开css自定义字体，个人用的隐藏图标和隐藏题头图。用的asri自带的，切换到其他主题，就没有字体渲染。arsi没有自带的渲染吗，切换主题后字体显示不一样

**Comment by mustakshif** [comment]
Asri主题默认字体和思源默认主题daylight、midnight字体是一样的，都是系统UI字体，是写味和任我行主题换了字体，所以看起来更细。如果更喜欢后者，可以使用自定代码片段

**Comment by tianxia704** [comment]
还真是，请问如何让字体显示的细一些，不会这个代码片段...

**Comment by tianxia704** [comment]
还有请问arsi是怎么合并顶栏，这个代码段是什么

**Comment by mustakshif** [comment]
> 还真是，请问如何让字体显示的细一些，不会这个代码片段...

```css
:root {
    --b3-font-family: Roboto, 'Twitter Emoji', "Noto Sans SC", sans-serif, apple-system, BlinkMacSystemFont,"Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", sans-serif, "Apple Color Emoji", "Noto Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols"
}
```

> 还有请问arsi是怎么合并顶栏，这个代码段是什么

这个功能是和JS代码高度耦合的，没办法单独提取

**Comment by mustakshif** [comment]
不对，你用的是平板设备吗

**Comment by mustakshif** [comment]
如果你用的是平板那可能不是字体原因，用这个片段：
```css
body {
    -webkit-font-smoothing: antialiased;
}
```

**Comment by tianxia704** [comment]
好的，不是平板，Mac端

**Comment by mustakshif** [comment]
行的，mac 端也是用这个代码

> 如果你用的是平板那可能不是字体原因，用这个片段：
> 
> ```css
> body {
>     -webkit-font-smoothing: antialiased;
> }
> ```

**Comment by tianxia704** [comment]
好了，感谢
