### ISSUE TITLE
bug？奇怪的问题-笔记本的右箭菜单选项被精简，没有了“关闭”选项

### ISSUE THREAD

**Issue by luluciamk** [mustakshif/Asri#99]
大大，这个主题是特别这么设计的吗？
如图
![image](https://github.com/user-attachments/assets/b1c230ce-33da-4878-b4de-db69e4aba8fc)

原本这里应该有“闪卡”“关闭”两个选项的，今天正式使用时，我才发现这两个选项没有了。
为了测试，开了另外的库，其他库的这个菜单选项是正常的。
然后，我以为仅仅只是asri这个主题的设计，于是更换其他主题，结果笔记本的右键菜单还是如上图，没有被变更回来。
这个非常奇怪啊。
这个是特意被精简了吗？
这个有必要精简吗？需要用的还是能用上，不需要用的，就多了两个选项，影响也不大啊。（另外还发现还有另外两个选项也被精简了——搜索和替换，虽说目前还没用过，但这些难道真的一点用也没有吗？以后说不定在某种场景下就能派上用场）
![image](https://github.com/user-attachments/assets/0923c14d-2bc4-4c9e-81df-0a3777d5fb11)
这个问题挺着急的，因为我笔记本很多，经常会关闭其中一些，使文档树精简点。

**Comment by luluciamk** [comment]
现在仔细观察，我发现arsi的文档树设计似乎会接管系统的文档树设计，因为更换其他主题后，文档树不止菜单弹窗，还有弹窗和文档树的字体，似乎都有点微妙的变化，不是我之前设置的那种尺寸（我用了“文档树自定义”这个插件）

**Comment by mustakshif** [comment]
我没有动过文档树相关的菜单选项，请检查是否是js代码片段或插件导致的

**Comment by luluciamk** [comment]
弄好了，感谢大大提醒。
